### PR TITLE
feat: apply automatically nutrition images insights

### PR DESCRIPTION
**Pull request by raphael0202**
Predictions are very good:
https://hunger.openfoodfacts.org/questions?type=nutrition_image

### CODE REVIEW

**Review by alexgarel — COMMENTED** [review]
@teolemon I think you should be the one approving this.

**Comment by teolemon** [comment]
It seems that it's been on since May, and has produced only 1K insights. What is the point of auto-application ?

**Comment by raphael0202** [comment]
It's 10 products fixed per day, and the risk is low :)

**Pull request merged**
