### PR TITLE
feat(main): correct and add label logos

### PR DESCRIPTION
**Pull request by nicorikken**
### What
Correct and provide label logo's.
At the moment some logo's couldn't be loaded in Hunger Games. These logo's are important to assist users matching logo's and help to guarantee data quality. Trying out Hunger Games some labels came up that didn't have logo's, so some of those are added too.

See individual commits for more details.

### Screenshot
Screenshot_20240316-223235_1
Hunger Games on mobile with logo that couldn't be loaded, showing placeholder text 'logo example' instead. Popover shows URL of image that couldn't be loaded.

### Fixes bug(s)
_Not applicable_

### Part of
_Not applicable_

### CODE REVIEW

**Comment by nicorikken** [comment]
I'd like to improve this pull-request by including all labels currently requested by Hunger Games for which an image is available. Maybe somebody here can provide me that list?

**Comment by raphael0202** [comment]
Thank you for contribution! I'm merging it, you can add new logos in a future PR

**Comment by raphael0202** [comment]
Here is the info you requested, obtained in production with:

```sql
SELECT value_tag, COUNT(*) as count
FROM product_insight
WHERE
type = 'label' and bounding_box IS NOT NULL
GROUP BY value_tag
ORDER BY count DESC;
```


| value_tag                                                               | count |
| ----------------------------------------------------------------------- | ----- |
| en:green-dot                                                            | 99673 |
| en:no-gluten                                                            | 67237 |
| fr:ab-agriculture-biologique                                            | 28024 |
| en:eu-organic                                                           | 27785 |
| en:nutriscore-grade-a                                                   | 27055 |
| en:nutriscore                                                           | 20195 |
| en:vegan                                                                | 16092 |
| en:usda-organic                                                         | 14479 |
| fr:triman                                                               | 12400 |
| en:pdo                                                                  | 10998 |
| en:nutriscore-grade-b                                                   | 10839 |
| en:french-poultry                                                       | 9603  |
| en:european-vegetarian-union-vegan                                      | 9499  |
| en:nutriscore-grade-c                                                   | 9249  |
| en:no-preservatives                                                     | 8234  |
| en:non-gmo-project                                                      | 8096  |
| en:nutriscore-grade-d                                                   | 7752  |
| en:the-vegan-society                                                    | 7118  |
| en:no-added-sugar                                                       | 6743  |
| en:nutriscore-grade-e                                                   | 6725  |
| en:made-in-france                                                       | 6670  |
| en:french-pork                                                          | 6590  |
| en:kosher                                                               | 6092  |
| de:eg-öko-verordnung                                                    | 6046  |
| en:rainforest-alliance                                                  | 5753  |
| en:no-lactose                                                           | 5750  |
| en:fair-trade                                                           | 5469  |
| en:eg-oko-verordnung                                                    | 5380  |
| en:no-colorings                                                         | 5004  |
| en:pgi                                                                  | 4984  |
| en:eu-non-eu-agriculture                                                | 4906  |
| en:fsc-mix                                                              | 4710  |
| en:fr-bio-01                                                            | 4546  |
| en:organic                                                              | 4510  |
| en:european-vegetarian-union                                            | 3613  |
| en:sustainable-seafood-msc                                              | 3268  |
| de:ohne-gentechnik                                                      | 3151  |
| en:utz-certified-cocoa                                                  | 2956  |
| en:made-in-italy                                                        | 2912  |
| en:fairtrade-international                                              | 2782  |
| fr:label-rouge                                                          | 2742  |
| en:canada-organic                                                       | 2563  |
| en:halal                                                                | 2521  |
| en:made-in-germany                                                      | 2382  |
| en:not-advised-for-pregnant-women                                       | 2275  |
| en:nutriscore-a                                                         | 2267  |
| fr:bleu-blanc-coeur                                                     | 1976  |
| en:french-beef                                                          | 1938  |
| en:no-artificial-flavors                                                | 1907  |
| en:responsible-aquaculture-asc                                          | 1862  |
| en:high-proteins                                                        | 1857  |
| en:qs-certification-mark                                                | 1768  |
| en:no-cholesterol                                                       | 1759  |
| en:australian-made                                                      | 1758  |
| en:produced-in-brittany                                                 | 1701  |
| en:suisse-garantie                                                      | 1633  |
| en:soil-association-organic                                             | 1465  |
| en:health-star-rating-4                                                 | 1441  |
| en:vegan-action                                                         | 1373  |
| en:nutriscore-b                                                         | 1340  |
| en:european-vegetarian-union-vegetarian                                 | 1320  |
| en:no-additives                                                         | 1318  |
| en:nutriscore-c                                                         | 1085  |
| en:certified-b-corporation                                              | 1077  |
| en:naturland                                                            | 1054  |
| en:cor-kosher                                                           | 1011  |
| en:demeter                                                              | 926   |
| en:bioland                                                              | 922   |
| en:nutriscore-d                                                         | 900   |
| en:fr-bio-10                                                            | 896   |
| en:sustainable-palm-oil                                                 | 852   |
| en:max-havelaar                                                         | 849   |
| en:roundtable-on-sustainable-palm-oil                                   | 836   |
| en:utz-certified                                                        | 824   |
| en:dolphin-safe                                                         | 823   |
| en:bio-suisse                                                           | 816   |
| en:made-in-belgium                                                      | 767   |
| en:health-star-rating-3-5                                               | 750   |
| en:catalan-council-of-organic-production                                | 744   |
| es:sin-tacc                                                             | 725   |
| fr:fruits-et-legumes-de-france                                          | 724   |
| de:bio-7-initiative                                                     | 718   |
| en:nutriscore-e                                                         | 716   |
| en:100-natural                                                          | 715   |
| en:orthodox-union-kosher                                                | 695   |
| en:dzg-gluten-free                                                      | 695   |
| en:made-in-spain                                                        | 678   |
| en:health-star-rating-5                                                 | 676   |
| en:fsc                                                                  | 659   |
| fr:saveurs-en-or                                                        | 634   |
| en:tsg                                                                  | 622   |
| en:made-in-the-eu                                                       | 561   |
| en:swiss-aoc                                                            | 558   |
| en:migros-bio                                                           | 552   |
| en:certified-gluten-free                                                | 519   |
| en:1-for-the-planet                                                     | 484   |
| en:ip-suisse                                                            | 475   |
| en:veganok                                                              | 471   |
| en:2018-gold-medal-of-the-german-agricultural-society                   | 458   |
| en:source-of-fibre                                                      | 457   |
| en:nl-bio-01                                                            | 449   |
| en:pefc                                                                 | 449   |
| en:it-bio-006                                                           | 424   |
| en:it-bio-009                                                           | 400   |
| en:keyhole                                                              | 394   |
| en:be-bio-01                                                            | 391   |
| en:green-dot-india                                                      | 368   |
| en:it-bio-007                                                           | 362   |
| en:certified-by-certipaq                                                | 358   |
| en:gb-org-05                                                            | 352   |
| en:high-fibres                                                          | 349   |
| en:potatoes-from-france                                                 | 337   |
| en:real-california-milk                                                 | 319   |
| en:no-flavors                                                           | 312   |
| en:health-star-rating-4-5                                               | 299   |
| en:no-palm-oil                                                          | 287   |
| en:made-in-mexico                                                       | 280   |
| en:fr-bio-09                                                            | 275   |
| en:metal-recycles-forever                                               | 274   |
| en:ch-bio-006                                                           | 259   |
| fr:haute-valeur-environnementale                                        | 256   |
| en:rspca-assured                                                        | 253   |
| en:es-eco-019-ct                                                        | 251   |
| en:utz-certified-coffee                                                 | 249   |
| en:certified-by-ecocert                                                 | 249   |
| en:terrasuisse                                                          | 245   |
| en:2020-gold-medal-of-the-german-agricultural-society                   | 237   |
| es:exceso-azucares                                                      | 236   |
| en:french-eggs                                                          | 234   |
| en:no-gmos                                                              | 223   |
| en:crossed-grain-symbol                                                 | 223   |
| de:pro-planet                                                           | 220   |
| es:comite-de-agricultura-ecologica-de-la-comunitat-valenciana           | 219   |
| en:co2e-neutral                                                         | 216   |
| es:exceso-calorias                                                      | 215   |
| en:health-star-rating-3                                                 | 214   |
| en:small-producers-symbol                                               | 213   |
| fr:lapin-francais                                                       | 209   |
| fr:agri-ethique-france                                                  | 203   |
| en:100-vegetable                                                        | 202   |
| es:exceso-sodio                                                         | 190   |
| en:at-bio-301                                                           | 184   |
| en:be-bio-02                                                            | 181   |
| en:kosher-parve                                                         | 176   |
| en:it-bio-014                                                           | 161   |
| en:swiss-pgi                                                            | 152   |
| de:haltungsform-4-premium                                               | 149   |
| es:comite-aragones-de-agricultura-ecologica                             | 145   |
| es:exceso-grasas-saturadas                                              | 144   |
| en:made-in-swiss                                                        | 144   |
| fr:aoc                                                                  | 144   |
| en:2019-gold-medal-of-the-german-agricultural-society                   | 139   |
| en:no-sugar                                                             | 138   |
| fr:societe-francaise-de-controle-de-viande-halal                        | 137   |
| en:health-star-rating-2                                                 | 137   |
| en:assured-food-standards                                               | 136   |
| en:star-k-kosher                                                        | 132   |
| en:low-fat                                                              | 127   |
| en:es-eco-020-cv                                                        | 126   |
| en:de-oko-001                                                           | 120   |
| en:pl-eko-07                                                            | 119   |
| en:health-star-rating-2-5                                               | 115   |
| en:no-soy                                                               | 114   |
| en:institut-fresenius                                                   | 114   |
| fr:produit-certifie                                                     | 112   |
| en:dk-øko-100                                                           | 111   |
| es:consejo-de-agricultura-ecologica-de-la-region-de-murcia              | 109   |
| en:no-milk                                                              | 106   |
| en:gb-org-02                                                            | 106   |
| en:eac                                                                  | 104   |
| en:it-bio-008                                                           | 102   |
| fr:tomates-de-france                                                    | 102   |
| en:gb-org-04                                                            | 100   |
| es:comite-de-agricultura-ecologica-de-la-comunidad-de-madrid            | 98    |
| en:ch-bio-038                                                           | 97    |
| en:omega-3                                                              | 96    |
| fr:controle-de-la-mosquee-d-evry-courcouronnes                          | 95    |
| en:eco-score-a                                                          | 94    |
| en:cocoa-life                                                           | 93    |
| en:no-trans-fat                                                         | 93    |
| en:lk-bio-149                                                           | 92    |
| en:no-fat                                                               | 92    |
| fr:association-rituelle-de-la-grande-mosquee-de-lyon                    | 89    |
| fr:afdiag                                                               | 85    |
| en:pl-eko-03                                                            | 84    |
| en:pl-eko-01                                                            | 84    |
| en:es-eco-001-an                                                        | 83    |
| en:british-lion-quality                                                 | 83    |
| en:calcium-source                                                       | 82    |
| fr:a-votre-service                                                      | 81    |
| en:certified-quality                                                    | 78    |
| en:vegetarian                                                           | 78    |
| en:health-star-rating-1-5                                               | 78    |
| en:not-recommended-for-children-under-3-years                           | 78    |
| fr:tidy-man                                                             | 77    |
| en:cz-bio-001                                                           | 76    |
| en:no-hydrogenated-fats                                                 | 76    |
| hr:povratna-naknada                                                     | 75    |
| en:naturland-fair                                                       | 75    |
| en:apples-from-france                                                   | 73    |
| en:de-oko-006                                                           | 73    |
| en:se-eko-01                                                            | 72    |
| fr:saveurs-de-l-annee                                                   | 72    |
| en:no-artificial-colors                                                 | 71    |
| en:animal-welfare                                                       | 71    |
| en:it-bio-002                                                           | 69    |
| en:french-meat                                                          | 68    |
| en:be-bio-03                                                            | 68    |
| es:recicla-amarillo                                                     | 68    |
| en:2017-gold-medal-of-the-german-agricultural-society                   | 66    |
| en:es-eco-001-cm                                                        | 66    |
| en:carbon-trust                                                         | 65    |
| en:es-eco-024-mu                                                        | 64    |
| en:superior-quality                                                     | 63    |
| en:austria-bio-garantie                                                 | 61    |
| en:es-eco-025-na                                                        | 60    |
| fr:legumes-de-france                                                    | 59    |
| fr:farine-de-ble-francais                                               | 59    |
| en:it-bio-005                                                           | 59    |
| en:no-added-salt                                                        | 58    |
| en:fr-bio-16                                                            | 57    |
| en:nestle-cocoa-plan                                                    | 56    |
| en:it-bio-004                                                           | 56    |
| en:de-oko-003                                                           | 56    |
| en:eu-agriculture                                                       | 56    |
| en:pt-bio-04                                                            | 56    |
| en:fr-bio-15                                                            | 55    |
| en:lt-eko-001                                                           | 54    |
| es:bienestar-animal                                                     | 53    |
| en:phosphore-source                                                     | 53    |
| en:at-bio-402                                                           | 52    |
| en:ch-bio-004                                                           | 51    |
| en:no-artificial-colours-and-preservatives                              | 51    |
| fr:bio-coherence                                                        | 51    |
| en:no-artificial-colours-or-flavours                                    | 50    |
| en:pgi-esparrago-de-navarra                                             | 50    |
| en:health-star-rating-1                                                 | 50    |
| en:bg-bio-22                                                            | 48    |
| en:natural-source-of-calcium                                            | 46    |
| en:halal-food-council-of-europe                                         | 45    |
| es:comite-de-agricultura-ecologica                                      | 45    |
| en:gr-bio-03                                                            | 44    |
| en:eu-ecolabel                                                          | 43    |
| en:carbon-trust-reducing-co2                                            | 43    |
| en:non-eu-agriculture                                                   | 42    |
| en:es-eco-016-cl                                                        | 41    |
| en:free-range-eggs                                                      | 40    |
| en:alimentos-de-extremadura                                             | 40    |
| en:reduced-salt                                                         | 39    |
| fr:viande-de-veau-francais                                              | 39    |
| en:health-star-rating-0-5                                               | 38    |
| en:it-bio-015                                                           | 38    |
| en:ie-org-02                                                            | 38    |
| en:de-oko-007                                                           | 37    |
| en:eco-score-b                                                          | 37    |
| en:pure-butter                                                          | 37    |
| en:certified-belgian-abbey-beer                                         | 36    |
| en:fr-bio-12                                                            | 36    |
| fr:nature-et-progres                                                    | 36    |
| en:gr-bio-01                                                            | 36    |
| en:pl-eko-06                                                            | 35    |
| en:de-oko-005                                                           | 35    |
| en:cz-bio-002                                                           | 34    |
| en:gost                                                                 | 33    |
| en:rainforest-alliance-cocoa                                            | 33    |
| en:fr-bio-07                                                            | 33    |
| en:gold-medal-of-the-german-agricultural-society                        | 31    |
| en:pt-bio-03                                                            | 30    |
| en:pl-eko-09                                                            | 30    |
| en:no-øko-01                                                            | 29    |
| en:es-eco-003-an                                                        | 29    |
| en:ie-org-03                                                            | 29    |
| en:at-bio-902                                                           | 28    |
| en:es-eco-022-ga                                                        | 27    |
| en:no-msg                                                               | 27    |
| en:pdo-chufa-de-valencia                                                | 27    |
| en:es-eco-014-ic                                                        | 26    |
| en:hr-eko-07                                                            | 26    |
| en:iso-9001                                                             | 26    |
| en:iso-22000                                                            | 25    |
| en:it-bio-012                                                           | 24    |
| en:es-eco-002-cm                                                        | 24    |
| en:charte-lu-harmony                                                    | 24    |
| en:cn-bio-141                                                           | 24    |
| en:2021-gold-medal-of-the-german-agricultural-society                   | 24    |
| en:cn-bio-154                                                           | 23    |
| en:fi-eko-201                                                           | 23    |
| en:french-duck                                                          | 22    |
| en:fr-bio-13                                                            | 22    |
| en:it-bio-013                                                           | 22    |
| en:es-eco-015-cn                                                        | 22    |
| en:low-salt                                                             | 22    |
| en:pasteurized                                                          | 22    |
| en:vegan-australia                                                      | 21    |
| en:lv-bio-01                                                            | 21    |
| en:bee-friendly                                                         | 20    |
| en:es-eco-023-ma                                                        | 20    |
| en:es-eco-002-an                                                        | 20    |
| en:es-eco-029-an                                                        | 20    |
| hr:živjeti-zdravo                                                       | 19    |
| en:si-eko-001                                                           | 19    |
| en:hr-eko-04                                                            | 19    |
| en:si-eko-004                                                           | 19    |
| hr:hrvatska-kvaliteta                                                   | 19    |
| en:eve-vegan                                                            | 19    |
| en:tr-bio-154                                                           | 18    |
| hr:mlijeko-hrvatskih-farmi                                              | 18    |
| en:pt-bio-02                                                            | 18    |
| en:bg-bio-02                                                            | 18    |
| en:nutriscore-experiment-grade-a                                        | 18    |
| en:2016-gold-medal-of-the-german-agricultural-society                   | 17    |
| en:ec-bio-141                                                           | 17    |
| en:th-bio-121                                                           | 17    |
| en:without-sulfites                                                     | 17    |
| en:biogarantie                                                          | 17    |
| en:si-eko-002                                                           | 16    |
| en:es-eco-028-cm                                                        | 16    |
| en:2014-gold-medal-of-the-german-agricultural-society                   | 16    |
| en:pdo-arroz-de-valencia                                                | 16    |
| en:cz-bio-003                                                           | 16    |
| en:de-oko-039                                                           | 16    |
| en:pl-eko-02                                                            | 16    |
| en:nutriscore-experiment-grade-b                                        | 16    |
| en:tr-bio-141                                                           | 16    |
| en:carbon-compensated-product                                           | 16    |
| en:gr-bio-15                                                            | 16    |
| en:source-of-iron                                                       | 15    |
| en:low-sugar                                                            | 15    |
| en:mg-bio-154                                                           | 15    |
| en:es-eco-026-vas                                                       | 15    |
| en:pl-eko-08                                                            | 15    |
| en:gr-bio-13                                                            | 15    |
| en:gb-org-17                                                            | 15    |
| en:sk-bio-002                                                           | 15    |
| en:gb-org-06                                                            | 14    |
| en:in-bio-147                                                           | 14    |
| en:new                                                                  | 14    |
| en:belgian-family-brewers                                               | 14    |
| en:2022-gold-medal-of-the-german-agricultural-society                   | 14    |
| en:de-oko-013                                                           | 14    |
| en:kashrut-division-of-the-london-beth-din                              | 13    |
| en:ma-bio-154                                                           | 13    |
| en:es-eco-006-ar                                                        | 13    |
| en:gr-bio-05                                                            | 13    |
| en:carbon-trust-carbon-neutral                                          | 13    |
| en:hu-oko-01                                                            | 13    |
| en:es-eco-002-cl                                                        | 12    |
| en:at-bio-901                                                           | 12    |
| en:es-eco-010-ar                                                        | 12    |
| en:pl-eko-04                                                            | 12    |
| fr:mais-de-france                                                       | 12    |
| en:es-eco-031-cl                                                        | 11    |
| en:ch-bio-086                                                           | 11    |
| fr:bio-equitable                                                        | 11    |
| en:mx-bio-141                                                           | 11    |
| en:pl-eko-05                                                            | 11    |
| en:nutriscore-experiment-grade-d                                        | 11    |
| en:no-caffeine                                                          | 11    |
| en:bg-bio-18                                                            | 10    |
| en:de-oko-037                                                           | 10    |
| en:si-eko-003                                                           | 10    |
| en:at-bio-501                                                           | 10    |
| en:bg-bio-14                                                            | 9     |
| en:organized-kashrut-kosher                                             | 9     |
| en:es-eco-004-an                                                        | 9     |
| en:es-eco-021-ex                                                        | 9     |
| en:se-eko-03                                                            | 9     |
| en:cn-bio-140                                                           | 9     |
| en:rs-bio-162                                                           | 8     |
| en:vn-bio-149                                                           | 8     |
| fr:fabrique-en-gourmandie                                               | 8     |
| en:es-eco-002-ar                                                        | 8     |
| en:es-eco-027-ri                                                        | 8     |
| en:2015-gold-medal-of-the-german-agricultural-society                   | 8     |
| en:bio-austria                                                          | 8     |
| en:eco-score-c                                                          | 8     |
| en:fed-without-gmos                                                     | 8     |
| en:th-bio-132                                                           | 8     |
| en:no-peanuts                                                           | 8     |
| en:th-bio-140                                                           | 8     |
| en:at-bio-401                                                           | 8     |
| en:lu-bio-06                                                            | 8     |
| en:es-eco-012-as                                                        | 8     |
| en:no-added-msg                                                         | 7     |
| en:enriched-wih-vitamins                                                | 7     |
| en:th-bio-154                                                           | 7     |
| en:transformed-in-france                                                | 7     |
| en:in-bio-134                                                           | 6     |
| en:in-bio-149                                                           | 6     |
| en:mx-bio-132                                                           | 6     |
| en:pt-bio-10                                                            | 6     |
| en:co-bio-154                                                           | 6     |
| en:lu-bio-04                                                            | 6     |
| hr:jaja-hrvatskih-farmi                                                 | 6     |
| en:tr-bio-161                                                           | 5     |
| en:ph-bio-154                                                           | 5     |
| en:pe-bio-141                                                           | 5     |
| en:no-artificial-preservatives                                          | 5     |
| en:fsc-recycling                                                        | 5     |
| fr:saveurs-de-l-annee-2018                                              | 5     |
| en:reduced-fat                                                          | 5     |
| en:it-bio-003                                                           | 5     |
| en:co-bio-141                                                           | 5     |
| en:es-eco-029-cl                                                        | 5     |
| en:lv-bio-02                                                            | 5     |
| en:bg-bio-16                                                            | 5     |
| en:cy-bio-001                                                           | 5     |
| en:reduced-sugar                                                        | 5     |
| en:se-eko-04                                                            | 5     |
| en:br-bio-154                                                           | 4     |
| en:bg-bio-07                                                            | 4     |
| en:za-bio-154                                                           | 4     |
| en:pe-bio-149                                                           | 4     |
| en:de-oko-044                                                           | 4     |
| en:de-oko-034                                                           | 4     |
| fr:viande-ovine-francaise                                               | 4     |
| hr:brašno-hrvatskih-polja                                               | 4     |
| hr:chief-rabbi-kotel-da-don                                             | 4     |
| en:pe-bio-118                                                           | 4     |
| en:bo-bio-123                                                           | 4     |
| en:gr-bio-18                                                            | 4     |
| en:tr-bio-175                                                           | 4     |
| en:es-eco-005-an                                                        | 4     |
| en:2013-gold-medal-of-the-german-agricultural-society                   | 4     |
| en:jp-bio-154                                                           | 4     |
| en:2019-silver-medal-of-the-german-agricultural-society                 | 4     |
| en:tn-bio-154                                                           | 3     |
| en:de-oko-012                                                           | 3     |
| en:gr-bio-02                                                            | 3     |
| hr:meso-hrvatskih-farmi-rođeno-i-uzgojeno-u-rh                          | 3     |
| en:se-eko-08                                                            | 3     |
| en:es-eco-013-ib                                                        | 3     |
| en:gmos                                                                 | 3     |
| en:es-eco-011-an                                                        | 3     |
| en:at-bio-302                                                           | 3     |
| en:es-eco-005-ar                                                        | 3     |
| en:ae-bio-154                                                           | 3     |
| hr:hrvatski-otočni-proizvod                                             | 3     |
| hr:ekološkog-proizvoda                                                  | 3     |
| en:ph-bio-141                                                           | 3     |
| en:low-sodium                                                           | 3     |
| en:bg-bio-04                                                            | 3     |
| en:silver-medal-of-the-german-agricultural-society                      | 3     |
| en:ir-bio-154                                                           | 3     |
| en:pt-bio-09                                                            | 3     |
| en:hu-oko-02                                                            | 3     |
| en:id-bio-149                                                           | 3     |
| en:hr-eko-01                                                            | 3     |
| en:2018-silver-medal-of-the-german-agricultural-society                 | 3     |
| en:sn-bio-141                                                           | 2     |
| en:tr-bio-140                                                           | 2     |
| sv:pant-1kr                                                             | 2     |
| en:gy-bio-154                                                           | 2     |
| en:lk-bio-143                                                           | 2     |
| en:gr-bio-06                                                            | 2     |
| en:vn-bio-132                                                           | 2     |
| en:am-bio-112                                                           | 2     |
| en:mx-bio-169                                                           | 2     |
| en:lb-bio-102                                                           | 2     |
| en:za-bio-140                                                           | 2     |
| en:ge-bio-141                                                           | 2     |
| en:ph-bio-102                                                           | 2     |
| en:cl-bio-110                                                           | 2     |
| en:cm-bio-154                                                           | 2     |
| en:se-eko-05                                                            | 2     |
| en:se-eko-07                                                            | 2     |
| es:recicla-azul                                                         | 2     |
| en:ph-bio-140                                                           | 2     |
| en:es-eco-008-ar                                                        | 2     |
| en:sk-bio-003                                                           | 2     |
| en:ec-bio-144                                                           | 2     |
| en:dz-bio-154                                                           | 2     |
| en:do-bio-149                                                           | 2     |
| en:in-bio-154                                                           | 2     |
| en:lu-bio-05                                                            | 2     |
| en:sn-bio-154                                                           | 2     |
| en:in-bio-152                                                           | 2     |
| en:de-oko-070                                                           | 2     |
| en:de-oko-060                                                           | 2     |
| en:E                                                                    | 2     |
| en:br-bio-122                                                           | 2     |
| hr:dokazana-kvaliteta                                                   | 2     |
| en:de-oko-021                                                           | 2     |
| en:de-oko-009                                                           | 2     |
| en:au-bio-107                                                           | 2     |
| en:be-bio-04                                                            | 2     |
| en:pt-bio-05                                                            | 2     |
| en:th-bio-149                                                           | 2     |
| en:ma-bio-102                                                           | 2     |
| en:hr-eko-03                                                            | 2     |
| en:nutriscore-experiment-grade-e                                        | 1     |
| en:nutriscore-experiment-grade-c                                        | 1     |
| en:bd-bio-149                                                           | 1     |
| en:bf-bio-154                                                           | 1     |
| en:no-flavour-enhancer                                                  | 1     |
| en:pe-bio-123                                                           | 1     |
| en:pe-bio-140                                                           | 1     |
| en:pe-bio-154                                                           | 1     |
| en:pe-bio-178                                                           | 1     |
| en:pf-bio-149                                                           | 1     |
| en:no-artificial-additives                                              | 1     |
| en:no-alcohol                                                           | 1     |
| en:ph-bio-149                                                           | 1     |
| en:bg-bio-19                                                            | 1     |
| en:contains-milk                                                        | 1     |
| en:no-added-fat                                                         | 1     |
| en:mx-bio-123                                                           | 1     |
| en:mx-bio-113                                                           | 1     |
| en:mx-bio-105                                                           | 1     |
| en:mv-bio-149                                                           | 1     |
| en:mk-bio-149                                                           | 1     |
| en:bo-bio-140                                                           | 1     |
| en:ps-bio-149                                                           | 1     |
| en:ps-bio-154                                                           | 1     |
| en:ma-bio-143                                                           | 1     |
| en:pt-bio-07                                                            | 1     |
| en:pt-bio-08                                                            | 1     |
| en:rainforest-alliance-black-tea                                        | 1     |
| en:refrigerated                                                         | 1     |
| en:ro-eco-007                                                           | 1     |
| en:ro-eco-008                                                           | 1     |
| en:rs-bio-101                                                           | 1     |
| en:rs-bio-140                                                           | 1     |
| en:rs-bio-154                                                           | 1     |
| en:la-bio-149                                                           | 1     |
| en:kw-bio-154                                                           | 1     |
| en:kr-bio-149                                                           | 1     |
| en:kh-bio-154                                                           | 1     |
| en:kh-bio-141                                                           | 1     |
| en:ke-bio-134                                                           | 1     |
| en:ie-org-04                                                            | 1     |
| en:30-less-sugar                                                        | 1     |
| en:id-bio-154                                                           | 1     |
| en:id-bio-140                                                           | 1     |
| en:ht-bio-154                                                           | 1     |
| en:hr-eko-09                                                            | 1     |
| en:hr-eko-05                                                            | 1     |
| en:th-bio-141                                                           | 1     |
| it:icea-bio-vegan                                                       | 1     |
| en:tr-bio-102                                                           | 1     |
| en:tr-bio-132                                                           | 1     |
| en:cd-bio-154                                                           | 1     |
| en:tw-bio-140                                                           | 1     |
| en:tz-bio-154                                                           | 1     |
| en:ua-bio-108                                                           | 1     |
| en:gr-bio-12                                                            | 1     |
| en:2016-silver-medal-of-the-german-agricultural-society                 | 1     |
| en:gh-bio-154                                                           | 1     |
| en:gh-bio-149                                                           | 1     |
| en:vn-bio-154                                                           | 1     |
| en:with-sunflower-oil                                                   | 1     |
| en:get-the-facts-drink-wise                                             | 1     |
| en:world-beer-awards-2014                                               | 1     |
| en:world-beer-awards-2019                                               | 1     |
| en:gd-bio-140                                                           | 1     |
| en:french-milk                                                          | 1     |
| en:french-agriculture                                                   | 1     |
| en:free-range-chicken                                                   | 1     |
| en:ci-bio-154                                                           | 1     |
| es:exceso-grasas-trans                                                  | 1     |
| en:cn-bio-107                                                           | 1     |
| en:co-bio-104                                                           | 1     |
| en:es-eco-028-an                                                        | 1     |
| en:es-eco-011-ar                                                        | 1     |
| en:eg-bio-149                                                           | 1     |
| en:ee-oko-02                                                            | 1     |
| en:eco-score-e                                                          | 1     |
| en:eco-score-d                                                          | 1     |
| en:ec-bio-149                                                           | 1     |
| fr:indication-geographique-protegee-de-la-republique-populaire-de-chine | 1     |
| fr:medaille-d-argent-du-concours-general-agricole-2019                  | 1     |
| fr:medaille-d-or-du-concours-general-agricole-2018                      | 1     |
| en:do-bio-141                                                           | 1     |
| fr:origine-france                                                       | 1     |
| en:do-bio-123                                                           | 1     |
| de:ohne-gentechnik-hergestellt                                          | 1     |
| en:de-oko-024                                                           | 1     |
| fr:viande-chevaline-francaise                                           | 1     |
| fr:viande-de-chevre-francaise                                           | 1     |
| en:de-oko-022                                                           | 1     |
| en:at-bio-701                                                           | 1     |

**Comment by nicorikken** [comment]
@raphael0202 thank you so much for the query result, that will help me prioritize additional contributions.

**Pull request merged**
